language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer install
script: php vendor/bin/phpunit
